veraneio/config/routes.rb
Rails.application.routes.draw do
	# Rotas para controle de login/logout
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	# Rota para cadastro
	get 'cadastro', to: 'estudantes#new', as: 'cadastro'

	# Rota padrao
	root "sessions#new"

	# Rotas das paginas de estudante e seu trabalho
	resources :estudantes, only: [:create, :new, :show, :update] do
		resources :trabalhos, only: [:create, :new, :show, :destroy, :update]
	end

	# Rotas para os professores
	get 'professores/:professor_id/avaliacao/:trabalho_id', to: 'professores/avaliacao#index', as: 'avaliacao'
	resources :professores do
		resources :trabalhos, controller: 'professores/trabalhos' do
			resources :pareceres
		end
	end

	# Rotas para as paginas de Admin
	namespace 'admin' do
		resources :professores
		resources :trabalhos do
		  get 'reenviar_email/:professor_id',to: 'trabalhos#reenviar_email' ,as: 'reenviar'
		end
		resources :estudantes
		resources :periodos
	end

	# Rotas para a leitura de pdf
	mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

veraneio/app/models/trabalho.rb
class Trabalho < ActiveRecord::Base
  belongs_to :estudante
  belongs_to :orientador, class_name: 'Professor'
  belongs_to :banca_1, class_name: 'Professor'
  belongs_to :banca_2, class_name: 'Professor'
  
  has_many :pareceres

  accepts_nested_attributes_for :orientador
  accepts_nested_attributes_for :banca_1
  accepts_nested_attributes_for :banca_2

  validates :titulo, presence: true
  validates :estudante, presence: true
  validates :orientador, presence: true

  has_attached_file :arquivo
  validates :arquivo, attachment_presence: true
  validates_attachment_content_type :arquivo, content_type: ['application/pdf']

  def avaliado_por_todos?
    !self.nota_banca_1.nil? and !self.nota_banca_2.nil? and !self.nota_orientador.nil?
  end

end

veraneio/app/controllers/admin/trabalhos_controller.rb
class Admin::TrabalhosController < ApplicationController
    layout 'admin'
    require 'my_string'

    def index
        @trabalhos_recebidos = Trabalho.order('updated_at DESC').all.where(estado: "Recebido do Aluno")
        @trabalhos_enviados = Trabalho.order('updated_at DESC').all.where(estado: "Enviado para Avaliação")
        @trabalhos_avaliados = Trabalho.order('updated_at DESC').all.where(estado: "Avaliado")
        @trabalhos_disponibilizados = Trabalho.order('updated_at DESC').all.where(estado: "Nota Disponibilizada")

        @professores = Professor.all
        @count_recebidos = Trabalho.where(estado: "Recebido do Aluno").count
        @count_avaliacao = Trabalho.where(estado: "Enviado para Avaliação").count
        @count_avaliado = Trabalho.where(estado: "Avaliado").count
        @count_disponivel = Trabalho.where(estado: "Nota Disponibilizada").count
    end

    def edit
        redirect_to root_path
    end

    def verifica_entrada
        params[:trabalho][:nota_disciplina].numeric? and params[:trabalho][:nota_disciplina].to_f >= 0 and params[:trabalho][:nota_disciplina].to_f <= 10
    end

    def update
        @trabalho = Trabalho.find params[:id]
        @estudante = Estudante.where(:trabalho == @trabalho.id).first

        if @trabalho.estado == "Recebido do Aluno"
            @banca_1 = Professor.find_by(id: params[:trabalho][:banca_1])
            @banca_2 = Professor.find_by(id: params[:trabalho][:banca_2])
            @orientador = @trabalho.orientador
            
            if @banca_1.email.nil? or @banca_2.email.nil?
                flash[:alert] = "Algum email vazio!"
            
            elsif @banca_1.email != @banca_2.email and @banca_1.email != @orientador.email and @banca_2.email != @orientador.email
                @trabalho.banca_1 = @banca_1
                @trabalho.banca_2 = @banca_2

                Thread.new do
                    Notificador.banca_avaliacao(@trabalho.estudante, @orientador).deliver_now
                    Notificador.banca_avaliacao(@trabalho.estudante, @banca_1).deliver_now
                    Notificador.banca_avaliacao(@trabalho.estudante, @banca_2).deliver_now
                end
                @trabalho.update estado: "Enviado para Avaliação"
                flash[:notice] = "Trabalho enviado com sucesso!"
            else
                flash[:alert] = "Professores iguais!"
            end

        elsif @trabalho.estado == "Avaliado"

            if params[:trabalho][:nota_disciplina] == ""
                flash[:notice] = "Campo Nota vazio!"
            
            elsif verifica_entrada
                @trabalho.nota_disciplina = params[:trabalho][:nota_disciplina]
                @trabalho.nota_final = ((@trabalho.nota_banca_1 + @trabalho.nota_banca_2)/2 + @trabalho.nota_orientador + @trabalho.nota_disciplina)/3
                @trabalho.save
                @trabalho.update estado: "Nota Disponibilizada"
                flash[:notice] = "Agora o #{@estudante.nome} pode ver sua nota!"
            end
        elsif @trabalho.estado == "Nota Disponibilizada"
            @trabalho.update estado: "Avaliado"
            flash[:notice] = "Trabalho em Revisão"
        end
        redirect_to admin_trabalhos_path
    end

	def reenviar_email
		professor = Professor.find(params[:professor_id])
		trabalho = Trabalho.find(params[:trabalho_id])
		Thread.new do
			Notificador.banca_avaliacao(trabalho.estudante, professor).deliver_now
		end
		redirect_to admin_trabalhos_path
	end

    private
    def trabalhos_param
        params.require(:trabalho).permit(:orientador, :banca_1, :banca_2)
    end
end

veraneio/app/controllers/professores/trabalhos_controller.rb
class Professores::TrabalhosController < ApplicationController
    layout 'professor'
    require 'my_string'
    
    def index
        @professor = Professor.find(params[:professor_id])
        @trabalhos_orientador = Trabalho.where(orientador: params[:professor_id]).where.not(estado: "Recebido do Aluno")
		@trabalhos_banca_1 = Trabalho.where(banca_1: params[:professor_id]).where.not(estado: "Recebido do Aluno")
		@trabalhos_banca_2 = Trabalho.where(banca_2: params[:professor_id]).where.not(estado: "Recebido do Aluno")
        @periodo_atual = Periodo.where(termino: Periodo.maximum('termino')).first
    end

    def verifica_entrada
        params[:trabalho][:nota].numeric? and params[:trabalho][:nota].to_f >= 0 and params[:trabalho][:nota].to_f <= 10
    end

    def create
        @professor = Professor.find(params[:professor_id])
        @trabalho = Trabalho.find(params[:trabalho][:id])

        if params[:trabalho][:nota] == ""
            flash[:notice] = "Campo Nota vazio!"
        

        elsif @trabalho.banca_1.id == @professor.id
            if verifica_entrada
                @trabalho.nota_banca_1 = params[:trabalho][:nota]
                @trabalho.save
            end
        
        elsif @trabalho.banca_2.id == @professor.id
            if verifica_entrada
                @trabalho.nota_banca_2 = params[:trabalho][:nota]
                @trabalho.save
            end
        
        elsif @trabalho.orientador.id == @professor.id
            if verifica_entrada
                @trabalho.nota_orientador = params[:trabalho][:nota]
                @trabalho.save
            end
        end
        
        if @trabalho.avaliado_por_todos?
            @trabalho.estado = "Avaliado"
            @trabalho.save
        else
            @trabalho.estado = "Enviado para Avaliação"
            @trabalho.save
        end
        redirect_to professor_trabalhos_path(params[:professor_id])
    end

    def update

    end


end

veraneio/app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController
	include Admin::PeriodosHelper
	before_action :set_estudante
	before_action :autenticar_usuario!, only: [:edit, :show, :update, :create]

	def new
		@trabalho = @estudante.build_trabalho
		@trabalho.build_orientador
		@trabalho.build_banca_1
		@trabalho.build_banca_2
		@periodo_maximo = Periodo.order(:termino).last
	end

	def show
		@trabalho = @estudante.trabalho
		@orientador = @trabalho.orientador
		@banca_1 = @trabalho.banca_1 || @trabalho.build_banca_1
		@banca_2 = @trabalho.banca_2 || @trabalho.build_banca_2
		@periodo_maximo = Periodo.order(:termino).last

		respond_to do |format|
			format.html { render 'edit' } 
		end
	end

	def create
		@horario_servidor = DateTime.now
		@periodo_maximo = Periodo.order(:termino).last.termino
		@trabalho = @estudante.build_trabalho(titulo: params[:trabalho][:titulo], arquivo: params[:trabalho][:arquivo])
		@orientador = Professor.where(email: params[:trabalho][:orientador_attributes][:email]).first
		@banca_1 = Professor.where(nome: params[:trabalho][:banca_1_attributes][:nome]).first
		@banca_2 = Professor.where(nome: params[:trabalho][:banca_2_attributes][:nome]).first

		verifica_se_existe_no_banco
		@trabalho.estado = "Recebido do Aluno"

		if @trabalho.save 
			@adm = Admin.first
			Thread.new do 
				Notificador.admin_novo_trabalho(@adm, @estudante).deliver_now
				Notificador.aluno_novo_trabalho(@trabalho,@estudante).deliver_now
			end
			log_out @usuario_atual
			flash[:notice] = "Trabalho enviado com sucesso!"
			redirect_to root_path
		else
			@banca_1 ||= @trabalho.build_banca_1
			@banca_2 ||= @trabalho.build_banca_2
			render 'new'
		end
	end

	def edit
		@trabalho = @estudante.trabalho
		@trabalho.banca_1 ||= @trabalho.build_banca_1
		@trabalho.banca_2 ||= @trabalho.build_banca_2
	end

	def update
		@horario_servidor = DateTime.now
		@periodo_maximo = Periodo.order(:termino).last.termino
		@trabalho = @estudante.trabalho
		@orientador = Professor.find_by(email: params[:trabalho][:orientador_attributes][:email])
		@banca_1 = Professor.find_by(nome: params[:trabalho][:banca_1_attributes][:nome])
		@banca_2 = Professor.find_by(nome: params[:trabalho][:banca_2_attributes][:nome])

		verifica_se_existe_no_banco

		@trabalho.titulo = params[:trabalho][:titulo]
		unless params[:trabalho][:arquivo].nil?
			@trabalho.arquivo = params[:trabalho][:arquivo]
		end

		respond_to do |format|
			if (@periodo_maximo >= @horario_servidor) and @trabalho.save
				flash.now[:notice] = "Seu trabalho foi atualizado com sucesso!"
				format.html { redirect_to estudante_trabalho_path @estudante, @trabalho }
			else
				@banca_1 ||= @trabalho.build_banca_1
				@banca_2 ||= @trabalho.build_banca_2
				format.html { render :edit }
			end
		end
	end

	private
	def trabalhos_param
		params.require(:trabalho).permit(:id, :titulo, :arquivo, orientador_attributes: [:nome, :email], banca_1_attributes: [:nome], banca_2_attributes: [:nome])
	end

	def set_estudante
		@estudante = Estudante.find(params[:estudante_id])
	end

	def verifica_se_existe_no_banco
		unless @orientador.nil?
			@trabalho.orientador = @orientador
		else
			@orientador = Professor.where(nome: trabalhos_param[:orientador_attributes][:nome]).first
			if @orientador
				@orientador.email = trabalhos_param[:orientador_attributes][:email]
			else
				@orientador = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
				@orientador.nome = trabalhos_param[:orientador_attributes][:nome]
				@orientador.email = trabalhos_param[:orientador_attributes][:email]
			end
			@orientador.save
			@trabalho.orientador = @orientador
		end

		if !@banca_1.nil?
			@trabalho.banca_1 = @banca_1
		elsif !params[:trabalho][:banca_1_attributes][:nome].empty?
			@banca_1 = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
			@banca_1.nome = trabalhos_param[:banca_1_attributes][:nome]
			@banca_1.save
			@trabalho.banca_1 = @banca_1
		end

		if !@banca_2.nil?
			@trabalho.banca_2 = @banca_2
		elsif !params[:trabalho][:banca_2_attributes][:nome].empty?
			@banca_2 = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
			@banca_2.nome = trabalhos_param[:banca_2_attributes][:nome]
			@banca_2.save
			@trabalho.banca_2 = @banca_2
		end
	end
end

veraneio/app/helpers/admin/trabalhos_helper.rb
module Admin::TrabalhosHelper
end

veraneio/app/helpers/professores/trabalhos_helper.rb
module Professores::TrabalhosHelper
end

veraneio/app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

veraneio/app/views/admin/trabalhos/_form.html.erb
<%= form_for ([:admin, trabalho]) do |t| %>
    <% if t.object.estado == "Recebido do Aluno" %>
        <div class="panel-body">
            <div role="form">
                <% if esta_periodo_aberto? and trabalho.estado == "Recebido do Aluno" %>
                    <div class="alert alert-danger">
						O período de recebimentos ainda está aberto.
					</div>
                <% else %>
                    <div class="alert alert-danger">
						O período de recebimentos se encerrou. É possível enviar trabalhos para avaliação!
					</div>
                <% end %>
                
                <div class="form-group">                            
                    <h4>
                        <ol class="breadcrumb">
                            <li> Orientador </li>
                        </ol>
                    
                        <%= t.select :orientador, options_for_select([t.object.orientador.nome]), {}, { class: "form form-group form-control" } %>
                        <ol class="breadcrumb">
                            <li>Avaliador 1</li>
                            <% if !t.object.banca_1.nil? %>
                                <li> Sugestao </li>
                                <li><%= t.object.banca_1.nome %></li>
                                <% if t.object.banca_1.email.nil? %>
                                    <li> Sem email </li>
                                <% else %>
                                    <li> <%= t.object.banca_1.email %></li>
                                <% end %>
                            <% end %>
                        </ol>
                        <% if t.object.banca_1.nil? %>
                            <%= t.collection_select :banca_1, Professor.all, :id, :nome_email, {include_blank: 'Ninguem selecionado'}, {class: "form form-group form-control"}  %>
                        <% else %>
                            <%= t.collection_select :banca_1, Professor.all, :id, :nome_email, {:selected => t.object.banca_1.id}, {class: "form form-group form-control"}  %>
                        <% end %>
                        <ol class="breadcrumb">
                            <li>Avaliador 2</li>
                            <% if !t.object.banca_2.nil? %>
                                <li> Sugestao </li>
                                <li><%= t.object.banca_2.nome %></li>
                                <% if t.object.banca_2.email.nil? %>
                                    <li> Sem email </li>
                                <% else %>
                                    <li> <%= t.object.banca_2.email %></li>
                                <% end %>
                            <% else %>
                                <li>Sem Sugestao</li>
                            <% end %>
                        </ol>
                    </h4>
                        <% if t.object.banca_2.nil? %>
                            <%= t.collection_select :banca_2, Professor.all, :id, :nome_email, {include_blank: 'Ninguem selecionado'}, { class: "form form-group form-control" } %>
                        <% else %>
                            <%= t.collection_select :banca_2, Professor.all, :id, :nome_email, {:selected => t.object.banca_2.id}, {class: "form form-group form-control"}  %>    
                        <% end %>
                        
                </div>
            </div>
            
            <%= link_to "Ver Professores", admin_professores_path, class: "btn btn-info" %>
            <% if !esta_periodo_aberto? %>
                <%= t.submit "Enviar para Avaliacao", class: 'form-group btn btn-danger pull-right' %>
            <% end %>
        </div>
    <% else %>
         <div class="panel-body">
            <div role="form">
                <% if trabalho.estado == "Enviado para Avaliação" %>
                    <div class="alert alert-warning">
						O trabalho está em avaliação. Quando estiver pronto, poderá disponibilizar a nota.
					</div>
                <% elsif esta_periodo_avaliacao_aberto? and trabalho.estado == "Avaliado" %>
                    <div class="alert alert-success">
						A avaliação do trabalho está completa, porém o prazo de avaliação ainda está aberto. Aguarde até o prazo se encerrar para poder disponibiliza-la.
					</div>
                <% elsif trabalho.estado == "Nota Disponibilizada" %>
                    <div class="alert alert-info">
						Caso haja alguma inconsistência, é possível é revisar a nota.
					</div>
                <% end %>

                <div class="form-group">
                    <h4>                            
                    <ol class="breadcrumb">
                        <li><%= link_to "Reenviar E-mail", admin_trabalho_reenviar_url(professor_id: t.object.orientador.id, trabalho_id: t.object.id), class: "btn btn-info" %></li>
                        <li>Orientador</li>
                        <li class=><%= t.object.orientador.nome %></li>
                        <% if t.object.nota_orientador.nil? %>
                            <li><span class="label label-warning">Aguardando Nota </span></li>
                        <% else %>
                            <li><span class="label label-success">Avaliado</span></li>
                            <li><span class="label label-default">Nota <%= t.object.nota_orientador %></span></li>
                        <% end %>
                    </ol>
                    <ol class="breadcrumb">
                        <li><%= link_to "Reenviar E-mail", admin_trabalho_reenviar_url(professor_id: t.object.banca_1.id, trabalho_id: t.object.id), class: "btn btn-info last-child" %></li>
                        <li>Avaliador 1</li>
                        <li><%= t.object.banca_1.nome %></li>
                        <% if t.object.nota_banca_1.nil? %>
                            <li><span class="label label-warning">Aguardando Nota </span></li>
                        <% else %>
                            <li><span class="label label-success">Avaliado</span></li>
                            <li><span class="label label-default">Nota <%= t.object.nota_banca_1 %></span></li>
                        <% end %>
                    </ol>
                    <ol class="breadcrumb">
                        <li ><%= link_to "Reenviar E-mail", admin_trabalho_reenviar_url(professor_id: t.object.banca_2.id, trabalho_id: t.object.id), class: "btn btn-info" %></li>
                        <li>Avaliador 2</li>
                        <li><%= t.object.banca_2.nome %></li>
                        <% if t.object.nota_banca_2.nil? %>
                            <li><span class="label label-warning">Aguardando Nota </span></li>
                        <% else %>
                            <li><span class="label label-success">Avaliado</span></li>
                            <li><span class="label label-default">Nota <%= t.object.nota_banca_2 %></span></li>
                        <% end %>
                    </ol>
                    <ol class="breadcrumb">
                        <li><span class="label label-info">Composição da Nota</span></li>
                        <li>(A+B+C)/3</li>
                        <li>Avaliadores
                            <% if !t.object.nota_banca_1.nil? and !t.object.nota_banca_2.nil? %>
                                <span class="label label-default">A = <%= (t.object.nota_banca_1 + t.object.nota_banca_2)/2 %></span>
                            <% end %>
                        </li>
                        <li>Orientador <span class="label label-default">B = <%= (t.object.nota_orientador) %> </span></li>
                        <li>Disciplina
                            <% if t.object.nota_disciplina.nil? %>
                                <span class="label label-default">C = Não Atribuida</span>
                            <% else %>
                                <span class="label label-default">C = <%= t.object.nota_disciplina %></span>
                            <% end %>
                        </li>
                        <li>
                            <% if !t.object.nota_final.nil? %>
                                <span class="label label-info"> NF = <%= t.object.nota_final.round(1) %></span>
                            <% end %>                        
                        </li>
                    </ol>
                    <% if t.object.estado == "Avaliado" %>
                        <ol class=breadcrumb>
                            <%= t.label :nota_da_disciplina %>
                            <%= t.text_field :nota_disciplina %>
                        <ol>
                    <% end %>
                    </h4>
                </div>
            </div>
            <% if t.object.estado == "Avaliado" and !esta_periodo_avaliacao_aberto? %>
                <%= t.submit "Disponibilizar Nota", class: 'form-group btn btn-success pull-right' %>
            <% elsif t.object.estado == "Nota Disponibilizada" %>
                <%= t.submit "Revisar Nota", class: 'form-group btn btn-success pull-right' %>
            <% end %>
        </div>
    <% end %>
<% end %>