veraneio/config/routes.rb
Rails.application.routes.draw do
	# Rotas para controle de login/logout
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	# Rota para cadastro
	get 'cadastro', to: 'estudantes#new', as: 'cadastro'

	# Rota padrao
	root "sessions#new"

	# Rotas das paginas de estudante e seu trabalho
	resources :estudantes, only: [:create, :new, :show, :update] do
		resources :trabalhos, only: [:create, :new, :show, :destroy, :update]
	end

	# Rotas para os professores
	get 'professores/:professor_id/avaliacao/:trabalho_id', to: 'professores/avaliacao#index', as: 'avaliacao'
	resources :professores do
		resources :trabalhos, controller: 'professores/trabalhos' do
			resources :pareceres
		end
	end

	# Rotas para as paginas de Admin
	namespace 'admin' do
		resources :professores
		resources :trabalhos do
		  get 'reenviar_email/:professor_id',to: 'trabalhos#reenviar_email' ,as: 'reenviar'
		end
		resources :estudantes
		resources :periodos
	end

	# Rotas para a leitura de pdf
	mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

veraneio/app/models/trabalho.rb
class Trabalho < ActiveRecord::Base
  belongs_to :estudante
  belongs_to :orientador, class_name: 'Professor'
  belongs_to :banca_1, class_name: 'Professor'
  belongs_to :banca_2, class_name: 'Professor'
  
  has_many :pareceres

  accepts_nested_attributes_for :orientador
  accepts_nested_attributes_for :banca_1
  accepts_nested_attributes_for :banca_2

  validates :titulo, presence: true
  validates :estudante, presence: true
  validates :orientador, presence: true

  has_attached_file :arquivo
  validates :arquivo, attachment_presence: true
  validates_attachment_content_type :arquivo, content_type: ['application/pdf']

  def avaliado_por_todos?
    !self.nota_banca_1.nil? and !self.nota_banca_2.nil? and !self.nota_orientador.nil?
  end

end

veraneio/app/controllers/admin/professores_controller.rb
class Admin::ProfessoresController < ApplicationController
	before_action :set_professor, only: [:update, :destroy, :edit]
    layout 'admin'
    
    def new
        @professor = Professor.new
    end

    def index
        @professor = Professor.new
        @professores = Professor.order('updated_at DESC').all
    end

	def edit
	end

	def destroy
        @em_orientacao = Trabalho.where(orientador: @professor.id)
        @em_avaliacao_1 = Trabalho.where(banca_1: @professor.id).where.not(estado: "Recebido do Aluno")
        @em_avaliacao_2 = Trabalho.where(banca_2: @professor.id).where.not(estado: "Recebido do Aluno")
        
        if @em_orientacao.empty? and @em_avaliacao_1.empty? and @em_avaliacao_2.empty?
            if @professor.destroy
                redirect_to admin_professores_path, notice: "Professor Excluido"
            else
                redirect_to admin_professores_path, notice: "Erro ao excluir Professor"
            end
        else
            redirect_to admin_professores_path, alert: "Não é possível excluir esse professor. Ele está em Orientação ou recebeu um Trabalho como Avaliador"
        end
	end

    def edit
		@professor = Professor.find(params[:id])
	end

    def update
        @professor = Professor.find(params[:id])
        if @professor.update professor_params
		  	flash[:notice] = "Professor atualizado com sucesso"
			redirect_to admin_professores_path
        else
		  	flash[:alert] = "Erro na atualização"
            redirect_to admin_professores_path
        end
    end

    private
	def set_professor
		@professor = Professor.find(params[:id])
	end
    def professor_params
        params.require(:professor).permit(:nome, :email)
    end
end

veraneio/app/controllers/admin/trabalhos_controller.rb
class Admin::TrabalhosController < ApplicationController
    layout 'admin'
    require 'my_string'

    def index
        @trabalhos_recebidos = Trabalho.order('updated_at DESC').all.where(estado: "Recebido do Aluno")
        @trabalhos_enviados = Trabalho.order('updated_at DESC').all.where(estado: "Enviado para Avaliação")
        @trabalhos_avaliados = Trabalho.order('updated_at DESC').all.where(estado: "Avaliado")
        @trabalhos_disponibilizados = Trabalho.order('updated_at DESC').all.where(estado: "Nota Disponibilizada")

        @professores = Professor.all
        @count_recebidos = Trabalho.where(estado: "Recebido do Aluno").count
        @count_avaliacao = Trabalho.where(estado: "Enviado para Avaliação").count
        @count_avaliado = Trabalho.where(estado: "Avaliado").count
        @count_disponivel = Trabalho.where(estado: "Nota Disponibilizada").count
    end

    def edit
        redirect_to root_path
    end

    def verifica_entrada
        params[:trabalho][:nota_disciplina].numeric? and params[:trabalho][:nota_disciplina].to_f >= 0 and params[:trabalho][:nota_disciplina].to_f <= 10
    end

    def update
        @trabalho = Trabalho.find params[:id]
        @estudante = Estudante.where(:trabalho == @trabalho.id).first

        if @trabalho.estado == "Recebido do Aluno"
            @banca_1 = Professor.find_by(id: params[:trabalho][:banca_1])
            @banca_2 = Professor.find_by(id: params[:trabalho][:banca_2])
            @orientador = @trabalho.orientador
            
            if @banca_1.email.nil? or @banca_2.email.nil?
                flash[:alert] = "Algum email vazio!"
            
            elsif @banca_1.email != @banca_2.email and @banca_1.email != @orientador.email and @banca_2.email != @orientador.email
                @trabalho.banca_1 = @banca_1
                @trabalho.banca_2 = @banca_2

                Thread.new do
                    Notificador.banca_avaliacao(@trabalho.estudante, @orientador).deliver_now
                    Notificador.banca_avaliacao(@trabalho.estudante, @banca_1).deliver_now
                    Notificador.banca_avaliacao(@trabalho.estudante, @banca_2).deliver_now
                end
                @trabalho.update estado: "Enviado para Avaliação"
                flash[:notice] = "Trabalho enviado com sucesso!"
            else
                flash[:alert] = "Professores iguais!"
            end

        elsif @trabalho.estado == "Avaliado"

            if params[:trabalho][:nota_disciplina] == ""
                flash[:notice] = "Campo Nota vazio!"
            
            elsif verifica_entrada
                @trabalho.nota_disciplina = params[:trabalho][:nota_disciplina]
                @trabalho.nota_final = ((@trabalho.nota_banca_1 + @trabalho.nota_banca_2)/2 + @trabalho.nota_orientador + @trabalho.nota_disciplina)/3
                @trabalho.save
                @trabalho.update estado: "Nota Disponibilizada"
                flash[:notice] = "Agora o #{@estudante.nome} pode ver sua nota!"
            end
        elsif @trabalho.estado == "Nota Disponibilizada"
            @trabalho.update estado: "Avaliado"
            flash[:notice] = "Trabalho em Revisão"
        end
        redirect_to admin_trabalhos_path
    end

	def reenviar_email
		professor = Professor.find(params[:professor_id])
		trabalho = Trabalho.find(params[:trabalho_id])
		Thread.new do
			Notificador.banca_avaliacao(trabalho.estudante, professor).deliver_now
		end
		redirect_to admin_trabalhos_path
	end

    private
    def trabalhos_param
        params.require(:trabalho).permit(:orientador, :banca_1, :banca_2)
    end
end

veraneio/app/controllers/professores/avaliacao_controller.rb
class Professores::AvaliacaoController < ApplicationController
    
    def index
        @professor = Professor.find(params[:professor_id])
        @trabalho = Trabalho.find(params[:trabalho_id])
        
        if @trabalho.orientador != @professor
            @pareceres = Parecer.where(professor_id: params[:professor_id], trabalho_id: params[:trabalho_id])
        else
            @pareceres = Parecer.where(trabalho_id: params[:trabalho_id])
        end
        @parecer = Parecer.new
    end

    def create
        @professor = Professor.find(params[:professor_id])
        @trabalho = Trabalho.find(params[:trabalho_id])
		@parecer = Parecer.new(pagina: params[:parecer][:pagina], texto: params[:parecer][:texto], professor: @professor, trabalho: @trabalho)
		
		if @parecer.save
			redirect_to avaliacao_path, notice: "Parecer salvo com sucesso"
		else
			redirect_to avaliacao_path, alert: "Erro ao salvar"
		end
	end
end

veraneio/app/controllers/professores/trabalhos_controller.rb
class Professores::TrabalhosController < ApplicationController
    layout 'professor'
    require 'my_string'
    
    def index
        @professor = Professor.find(params[:professor_id])
        @trabalhos_orientador = Trabalho.where(orientador: params[:professor_id]).where.not(estado: "Recebido do Aluno")
		@trabalhos_banca_1 = Trabalho.where(banca_1: params[:professor_id]).where.not(estado: "Recebido do Aluno")
		@trabalhos_banca_2 = Trabalho.where(banca_2: params[:professor_id]).where.not(estado: "Recebido do Aluno")
        @periodo_atual = Periodo.where(termino: Periodo.maximum('termino')).first
    end

    def verifica_entrada
        params[:trabalho][:nota].numeric? and params[:trabalho][:nota].to_f >= 0 and params[:trabalho][:nota].to_f <= 10
    end

    def create
        @professor = Professor.find(params[:professor_id])
        @trabalho = Trabalho.find(params[:trabalho][:id])

        if params[:trabalho][:nota] == ""
            flash[:notice] = "Campo Nota vazio!"
        

        elsif @trabalho.banca_1.id == @professor.id
            if verifica_entrada
                @trabalho.nota_banca_1 = params[:trabalho][:nota]
                @trabalho.save
            end
        
        elsif @trabalho.banca_2.id == @professor.id
            if verifica_entrada
                @trabalho.nota_banca_2 = params[:trabalho][:nota]
                @trabalho.save
            end
        
        elsif @trabalho.orientador.id == @professor.id
            if verifica_entrada
                @trabalho.nota_orientador = params[:trabalho][:nota]
                @trabalho.save
            end
        end
        
        if @trabalho.avaliado_por_todos?
            @trabalho.estado = "Avaliado"
            @trabalho.save
        else
            @trabalho.estado = "Enviado para Avaliação"
            @trabalho.save
        end
        redirect_to professor_trabalhos_path(params[:professor_id])
    end

    def update

    end


end

veraneio/app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
	before_action :set_professor, only: [:destroy]
	layout 'professor'

	def index
	end

	def show
		@professor = Professor.find(params[:id])
	end

	def new
		@professor = Professor.new
	end

	def create
		@professor = Professor.new(professor_params)
		@professor.password = 'professor'
		@professor.password_confirmation = 'professor'
		@professor.estado_acesso = "Não Confirmado"
		if @professor.save
			redirect_to admin_professores_path, notice: "Professor salvo com sucesso"
		else
			redirect_to admin_professores_path, alert: "Erro ao salvar"
		end
	end

	def update
        @professor = Professor.find(params[:id])
		@professor.estado_acesso = "Confirmado"
        if @professor.update professor_params
		  	flash[:notice] = "Professor atualizado com sucesso"
			redirect_to professor_path
        else
		  	flash[:alert] = "Erro na atualização"
            redirect_to professor_path
        end
    end


	private
	def set_professor
		@professor = Professor.find(params[:id])
	end

	def professor_params 
		params.require(:professor).permit(:nome, :email, :password, :password_confirmation)
	end

end

veraneio/app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController
	include Admin::PeriodosHelper
	before_action :set_estudante
	before_action :autenticar_usuario!, only: [:edit, :show, :update, :create]

	def new
		@trabalho = @estudante.build_trabalho
		@trabalho.build_orientador
		@trabalho.build_banca_1
		@trabalho.build_banca_2
		@periodo_maximo = Periodo.order(:termino).last
	end

	def show
		@trabalho = @estudante.trabalho
		@orientador = @trabalho.orientador
		@banca_1 = @trabalho.banca_1 || @trabalho.build_banca_1
		@banca_2 = @trabalho.banca_2 || @trabalho.build_banca_2
		@periodo_maximo = Periodo.order(:termino).last

		respond_to do |format|
			format.html { render 'edit' } 
		end
	end

	def create
		@horario_servidor = DateTime.now
		@periodo_maximo = Periodo.order(:termino).last.termino
		@trabalho = @estudante.build_trabalho(titulo: params[:trabalho][:titulo], arquivo: params[:trabalho][:arquivo])
		@orientador = Professor.where(email: params[:trabalho][:orientador_attributes][:email]).first
		@banca_1 = Professor.where(nome: params[:trabalho][:banca_1_attributes][:nome]).first
		@banca_2 = Professor.where(nome: params[:trabalho][:banca_2_attributes][:nome]).first

		verifica_se_existe_no_banco
		@trabalho.estado = "Recebido do Aluno"

		if @trabalho.save 
			@adm = Admin.first
			Thread.new do 
				Notificador.admin_novo_trabalho(@adm, @estudante).deliver_now
				Notificador.aluno_novo_trabalho(@trabalho,@estudante).deliver_now
			end
			log_out @usuario_atual
			flash[:notice] = "Trabalho enviado com sucesso!"
			redirect_to root_path
		else
			@banca_1 ||= @trabalho.build_banca_1
			@banca_2 ||= @trabalho.build_banca_2
			render 'new'
		end
	end

	def edit
		@trabalho = @estudante.trabalho
		@trabalho.banca_1 ||= @trabalho.build_banca_1
		@trabalho.banca_2 ||= @trabalho.build_banca_2
	end

	def update
		@horario_servidor = DateTime.now
		@periodo_maximo = Periodo.order(:termino).last.termino
		@trabalho = @estudante.trabalho
		@orientador = Professor.find_by(email: params[:trabalho][:orientador_attributes][:email])
		@banca_1 = Professor.find_by(nome: params[:trabalho][:banca_1_attributes][:nome])
		@banca_2 = Professor.find_by(nome: params[:trabalho][:banca_2_attributes][:nome])

		verifica_se_existe_no_banco

		@trabalho.titulo = params[:trabalho][:titulo]
		unless params[:trabalho][:arquivo].nil?
			@trabalho.arquivo = params[:trabalho][:arquivo]
		end

		respond_to do |format|
			if (@periodo_maximo >= @horario_servidor) and @trabalho.save
				flash.now[:notice] = "Seu trabalho foi atualizado com sucesso!"
				format.html { redirect_to estudante_trabalho_path @estudante, @trabalho }
			else
				@banca_1 ||= @trabalho.build_banca_1
				@banca_2 ||= @trabalho.build_banca_2
				format.html { render :edit }
			end
		end
	end

	private
	def trabalhos_param
		params.require(:trabalho).permit(:id, :titulo, :arquivo, orientador_attributes: [:nome, :email], banca_1_attributes: [:nome], banca_2_attributes: [:nome])
	end

	def set_estudante
		@estudante = Estudante.find(params[:estudante_id])
	end

	def verifica_se_existe_no_banco
		unless @orientador.nil?
			@trabalho.orientador = @orientador
		else
			@orientador = Professor.where(nome: trabalhos_param[:orientador_attributes][:nome]).first
			if @orientador
				@orientador.email = trabalhos_param[:orientador_attributes][:email]
			else
				@orientador = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
				@orientador.nome = trabalhos_param[:orientador_attributes][:nome]
				@orientador.email = trabalhos_param[:orientador_attributes][:email]
			end
			@orientador.save
			@trabalho.orientador = @orientador
		end

		if !@banca_1.nil?
			@trabalho.banca_1 = @banca_1
		elsif !params[:trabalho][:banca_1_attributes][:nome].empty?
			@banca_1 = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
			@banca_1.nome = trabalhos_param[:banca_1_attributes][:nome]
			@banca_1.save
			@trabalho.banca_1 = @banca_1
		end

		if !@banca_2.nil?
			@trabalho.banca_2 = @banca_2
		elsif !params[:trabalho][:banca_2_attributes][:nome].empty?
			@banca_2 = Professor.new password_digest: BCrypt::Password.create('professor', cost: 4), estado_acesso: "Não Confirmado"
			@banca_2.nome = trabalhos_param[:banca_2_attributes][:nome]
			@banca_2.save
			@trabalho.banca_2 = @banca_2
		end
	end
end

veraneio/app/helpers/admin/trabalhos_helper.rb
module Admin::TrabalhosHelper
end

veraneio/app/helpers/professores/avaliacao_helper.rb
module Professores::AvaliacaoHelper
    
end

veraneio/app/helpers/professores/trabalhos_helper.rb
module Professores::TrabalhosHelper
end

veraneio/app/helpers/professores_helper.rb
module ProfessoresHelper
end

veraneio/app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

veraneio/app/views/professores/trabalhos/_form.html.erb
<%= form_for (:trabalho) do |t| %>
    <div class="panel-body list-group-item">
        <% if trabalho.estado != "Recebido do Aluno" %>
            <h4>
            <ol class="breadcrumb">

                <% if trabalho.banca_1 == @professor %>
                    <% if trabalho.nota_banca_1.nil? %>
                        <li><span class="label label-warning"> Ainda sem nota </span></li>
                    <% else %>
                        <li><span class="label label-success"> Minha Nota <%= trabalho.nota_banca_1 %> </span></li>
                    <% end %>
                <% elsif trabalho.banca_2 == @professor %>
                    <% if trabalho.nota_banca_2.nil? %>
                        <li><span class="label label-warning"> Ainda sem nota </span></li>
                    <% else %>
                        <li><span class="label label-success"> Minha Nota <%= trabalho.nota_banca_2 %> </span></li>
                    <% end %>
                <% else %>
                    <% if trabalho.nota_orientador.nil? %>
                        <li><span class="label label-warning"> Ainda sem nota </span></li>
                    <% else %>
                        <li><span class="label label-success"> Minha Nota <%= trabalho.nota_orientador %> </span></li>
                    <% end %>
                <% end %>

                <li>Professor Orientador</li>
                <li><%= trabalho.orientador.nome %></li>
            </ol>
                
            <ol class="breadcrumb">
                <li>Aluno</li>
                <li> <%= trabalho.estudante.nome %> </li>
            </ol>
            <ol class="breadcrumb">
                <li>Titulo</li>
                <li> <%= trabalho.titulo %> </li>
            </ol>
            </h4>
        <% elsif trabalho.estado == "Encaminhado para o Orientador" %>
            <span class="label label-success">Avaliado</span>
        <% end %>

        <%= link_to "Abrir arquivo para avaliação", avaliacao_path(params[:professor_id], trabalho), class: 'btn btn-primary'%>
        <%= link_to "Abrir Pareceres", professor_trabalho_pareceres_path(params[:professor_id], trabalho), class: 'btn btn-primary' %>
        <% if esta_periodo_avaliacao_aberto? %>
            <%= t.label :nota %>
            <%= t.text_field :nota %>
            <%= t.hidden_field :id, value: trabalho.id %>
            <%= t.submit  class: 'btn btn-success pull-right' %>
        <% end %>
    </div>
<% end %>

veraneio/app/views/professores/trabalhos/index.html.erb
<% if notice %>
    <div class='alert alert-success'><%= notice %></div>
<% end %>

<% if esta_periodo_avaliacao_aberto? %>
	<div class="panel panel-success">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-11 text-left">
					<div>A nota da avaliação deve ser submetida com seus pareceres e sugestões até o dia <%= ultimo_periodo_avaliacao %>.</div>
				</div>
				<div class="col-xs-1">
					<i class="fa fa-comments fa-5x"></i>
					<span class="glyphicon glyphicon-pencil icon"></span>
				</div>
			</div>
		</div>
	</div>
<% else %>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<div class="row">
				<div class="col-xs-11 text-left">
					<div>O período de submissão expirou em <%= ultimo_periodo_avaliacao %>. Em casos de trabalhos não avaliados, não será possível atribuir a nota. Entre em contato com a Professora de TCC1.</div>
				</div>
				<div class="col-xs-1">
					<i class="fa fa-comments fa-5x"></i>
					<span class="glyphicon glyphicon-remove-circle icon"></span>
				</div>
			</div>
		</div>
	</div>
<% end %>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
	<div class="panel-heading ca">
	  <h4 class="panel-title">
		<a data-toggle="collapse" data-parent="#accordion" href="#accord1" class="cabecalho">
		  <h2> Orientador </h2>
      <h2> <%= @professor.nome %></h2>
		</a>
	  </h4>
	</div>
	<div id="accord1" class="panel-collapse collapse out">
	  <div class="panel-body">
			<ul class="list-group ">
				<% @trabalhos_orientador.each do |trabalho|%>
					<%= render 'form' , trabalho: trabalho %>
				<% end %>
			</ul>
	  </div>
	</div>
  </div>
</div>


<div class="panel-group" id="accordion">
  <div class="panel panel-default">
	<div class="panel-heading ca">
	  <h4 class="panel-title">
		<a data-toggle="collapse" data-parent="#accordion" href="#accord2" class="cabecalho">
		  <h2> Avaliador </h2>
		</a>
	  </h4>
	</div>
	<div id="accord2" class="panel-collapse collapse out">
	  <div class="panel-body">
		<ul class="list-group ">
		  <% @trabalhos_banca_1.each do |trabalho1|%>
				<%= render 'form' , trabalho: trabalho1 %>
			<% end %>

		  <% @trabalhos_banca_2.each do |trabalho2|%>
				<%= render 'form' , trabalho: trabalho2 %>
			<% end %>
		</ul>
	  </div>
	</div>
  </div>
</div>