veraneio/config/routes.rb
Rails.application.routes.draw do
	# Rotas para controle de login/logout
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	# Rota para cadastro
	get 'cadastro', to: 'estudantes#new', as: 'cadastro'

	# Rota padrao
	root "sessions#new"

	# Rotas das paginas de estudante e seu trabalho
	resources :estudantes, only: [:create, :new, :show, :update] do
		resources :trabalhos, only: [:create, :new, :show, :destroy, :update]
	end

	# Rotas para os professores
	get 'professores/:professor_id/avaliacao/:trabalho_id', to: 'professores/avaliacao#index', as: 'avaliacao'
	resources :professores do
		resources :trabalhos, controller: 'professores/trabalhos' do
			resources :pareceres
		end
	end

	# Rotas para as paginas de Admin
	namespace 'admin' do
		resources :professores
		resources :trabalhos do
		  get 'reenviar_email/:professor_id',to: 'trabalhos#reenviar_email' ,as: 'reenviar'
		end
		resources :estudantes
		resources :periodos
	end

	# Rotas para a leitura de pdf
	mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

veraneio/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Veraneio</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-7">
					<ul class="nav navbar-nav">
						<li class="<%= 'active' if current_page?(admin_trabalhos_path) %>"><%= link_to "Trabalhos", admin_trabalhos_path %></li>
						<li class="<%= 'active' if current_page?(admin_estudantes_path) %>"><%= link_to "Estudantes", admin_estudantes_path %></li>
						<li class="<%= 'active' if current_page?(admin_professores_path) %>"><%= link_to "Professores", admin_professores_path %></li>
						<li class="<%= 'active' if current_page?(admin_periodos_path) %>"><%= link_to "Períodos", admin_periodos_path %></li>
					</ul>
					<% if !current_page?(login_path) and tem_alguem_logado? %>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to "Sair", logout_path, method: :delete %></li>
						</ul>
					<% end %>
				</div>
			</div>
		</nav>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

veraneio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Veraneio</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<% if !current_page?(login_path) and tem_alguem_logado? %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-7">
	  <ul class="nav navbar-nav navbar-right">
		<li><%= link_to "Sair", logout_path, method: :delete %></li>
	  </ul>
	</div>
  </div>
</nav>
  <% end %>

<div class='container'>
  <%= yield %>
</div>
</body>

veraneio/app/views/layouts/professor.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Veraneio</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-7">
					<ul class="nav navbar-nav">
                        <% if params[:professor_id].nil? %>
                            <% params[:professor_id] = params[:id]%>
                        <% end %>
						<li class="<%= 'active' if current_page?(professor_trabalhos_path(params[:professor_id])) %>"><%= link_to "Trabalhos", professor_trabalhos_path(params[:professor_id]) %></li>
					</ul>
					<% if !current_page?(login_path) and tem_alguem_logado? %>
						<ul class="nav navbar-nav navbar-right">

							<li><%= link_to 'Minha Conta', professor_path(params[:professor_id]) %></li>
							<li><%= link_to "Sair", logout_path, method: :delete %></li>
						</ul>
					<% end %>
				</div>
			</div>
		</nav>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>