veraneio/config/routes.rb
Rails.application.routes.draw do
	# Rotas para controle de login/logout
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	# Rota para cadastro
	get 'cadastro', to: 'estudantes#new', as: 'cadastro'

	# Rota padrao
	root "sessions#new"

	# Rotas das paginas de estudante e seu trabalho
	resources :estudantes, only: [:create, :new, :show, :update] do
		resources :trabalhos, only: [:create, :new, :show, :destroy, :update]
	end

	# Rotas para os professores
	get 'professores/:professor_id/avaliacao/:trabalho_id', to: 'professores/avaliacao#index', as: 'avaliacao'
	resources :professores do
		resources :trabalhos, controller: 'professores/trabalhos' do
			resources :pareceres
		end
	end

	# Rotas para as paginas de Admin
	namespace 'admin' do
		resources :professores
		resources :trabalhos do
		  get 'reenviar_email/:professor_id',to: 'trabalhos#reenviar_email' ,as: 'reenviar'
		end
		resources :estudantes
		resources :periodos
	end

	# Rotas para a leitura de pdf
	mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

veraneio/app/views/notificador/admin_novo_trabalho.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body>
		<h1>Um novo arquivo de TCC foi enviado no sistema.</h1>
		<p>
		O aluno <%=@estudante.nome%> de RA: <%=@estudante.ra%> cadastrou o arquivo <%=@estudante.trabalho.titulo%> no sistema de TCC.</br>
		Para visualizar o trabalho clique <%=link_to "aqui" , estudante_trabalho_url({estudante_id: @estudante.id, id:@estudante.trabalho.id})%>
		</p>
	</body>
</html>

veraneio/app/views/notificador/aluno_novo_trabalho.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body>
		<h1>Seu projeto de TCC 1 foi enviado no sistema.</h1>
		<p>
		Olá <%= @estudante.nome %> , de RA: <%= @estudante.ra %>.
		</p>
		<p>
		Seu trabalho de TCC 1 de titulo <%= @trabalho.titulo %> foi enviado na data <%= Time.now %> para avaliacao.
		</p>
	</body>
</html>

veraneio/app/views/notificador/banca_avaliacao.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body>
		<h1>Um trabalho de TCC necessita de sua avaliação.</h1>
		<p>
		Um trabalho de TCC foi submetido para que seja avaliado por você.</br>
		Título do trabalho: <%=@estudante.trabalho.titulo%></br>
		Aluno <%=@estudante.nome%></br>
	       	RA: <%=@estudante.ra%></br>
		Para visualizar o trabalho clique <%=link_to "aqui" , estudante_trabalho_url({estudante_id: @estudante.id, id:@estudante.trabalho.id})%>
		</p>
	</body>
</html>

veraneio/app/views/notificador/envia_email.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body>
		<h1>Esse é um template de email</h1>
		<p>
		Vamos modificar este template para criar varios tipos de email<br>
		</p>
	</body>
</html>

veraneio/app/views/notificador/envia_email.text.erb
Este ainda é um template do email texto
===============================================
 
Modifiquemos este template para uso em cada email